# Generated by Django 3.2.12 on 2023-03-01 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='subitems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='SubOptions'), size=None),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Option Name'),
        ),
    ]
