# Generated by Django 3.2.12 on 2023-03-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230301_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='subitems',
            new_name='suboptions',
        ),
    ]
