# Generated by Django 3.2.12 on 2023-03-01 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_subitems_menumodel_suboptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='suboptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, verbose_name='SubOptions'), size=None),
        ),
    ]
