# Generated by Django 3.2.12 on 2023-03-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20230302_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusmodel',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
